# docker-compose.yml
version: "3.8"
services:
  registry-mirror:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io/v2/
    volumes:
      - mirror_data:/var/lib/registry
volumes:
  mirror_data: